// Copyright 2026 Ryan Collins. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type EmptyResponse struct {
	Errors json.RawMessage `json:"errors"`
}

type ErrorProto struct {
	Argument             json.RawMessage `json:"argument"`
	Code                 string          `json:"code"`
	DebugInfo            string          `json:"debugInfo"`
	Domain               string          `json:"domain"`
	ExternalErrorMessage string          `json:"externalErrorMessage"`
	Location             string          `json:"location"`
	LocationType         string          `json:"locationType"`
}

type Errors struct {
	Code      string          `json:"code"`
	Error     json.RawMessage `json:"error"`
	RequestId string          `json:"requestId"`
}

type Group struct {
	ContentDetails json.RawMessage `json:"contentDetails"`
	Errors         json.RawMessage `json:"errors"`
	Etag           string          `json:"etag"`
	Id             string          `json:"id"`
	Kind           string          `json:"kind"`
	Snippet        json.RawMessage `json:"snippet"`
}

type GroupContentDetails struct {
	ItemCount string `json:"itemCount"`
	ItemType  string `json:"itemType"`
}

type GroupItem struct {
	Errors   json.RawMessage `json:"errors"`
	Etag     string          `json:"etag"`
	GroupId  string          `json:"groupId"`
	Id       string          `json:"id"`
	Kind     string          `json:"kind"`
	Resource json.RawMessage `json:"resource"`
}

type GroupItemResource struct {
	Id   string `json:"id"`
	Kind string `json:"kind"`
}

type GroupSnippet struct {
	PublishedAt string `json:"publishedAt"`
	Title       string `json:"title"`
}

type ListGroupItemsResponse struct {
	Errors json.RawMessage `json:"errors"`
	Etag   string          `json:"etag"`
	Items  json.RawMessage `json:"items"`
	Kind   string          `json:"kind"`
}

type ListGroupsResponse struct {
	Errors        json.RawMessage `json:"errors"`
	Etag          string          `json:"etag"`
	Items         json.RawMessage `json:"items"`
	Kind          string          `json:"kind"`
	NextPageToken string          `json:"nextPageToken"`
}

type QueryResponse struct {
	ColumnHeaders json.RawMessage `json:"columnHeaders"`
	Errors        json.RawMessage `json:"errors"`
	Kind          string          `json:"kind"`
	Rows          json.RawMessage `json:"rows"`
}

type ResultTableColumnHeader struct {
	ColumnType string `json:"columnType"`
	DataType   string `json:"dataType"`
	Name       string `json:"name"`
}
