// Copyright 2026 ryandacoder. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"youtube-analytics-pp-cli/internal/cli"
	"youtube-analytics-pp-cli/internal/client"
	"youtube-analytics-pp-cli/internal/cliutil"
	"youtube-analytics-pp-cli/internal/config"
	"youtube-analytics-pp-cli/internal/mcp/cobratree"
	"youtube-analytics-pp-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("group-items_delete",
			mcplib.WithDescription("Removes an item from a group. Optional: id. Returns the EmptyResponse. Destructive."),
			mcplib.WithString("id", mcplib.Description("The `id` parameter specifies the YouTube group item ID of the group item that is being deleted.")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/v2/groupItems", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("group-items_insert",
			mcplib.WithDescription("Creates a group item. Optional: errors, etag, groupId (plus 3 more). Returns the new GroupItem."),
			mcplib.WithString("errors", mcplib.Description("Request Error information. The presence of an error field signals that the operation has failed.")),
			mcplib.WithString("etag", mcplib.Description("The Etag of this resource.")),
			mcplib.WithString("groupId", mcplib.Description("The ID that YouTube uses to uniquely identify the group that contains the item.")),
			mcplib.WithString("id", mcplib.Description("The ID that YouTube uses to uniquely identify the `channel`, `video`, `playlist`, or `asset` resource that is...")),
			mcplib.WithString("kind", mcplib.Description("Identifies the API resource's type. The value will be `youtube#groupItem`.")),
			mcplib.WithString("resource", mcplib.Description("Resource")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/v2/groupItems", false, []mcpParamBinding{{PublicName: "errors", WireName: "errors", Location: "body"}, {PublicName: "etag", WireName: "etag", Location: "body"}, {PublicName: "groupId", WireName: "groupId", Location: "body"}, {PublicName: "id", WireName: "id", Location: "body"}, {PublicName: "kind", WireName: "kind", Location: "body"}, {PublicName: "resource", WireName: "resource", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("group-items_list",
			mcplib.WithDescription("Returns a collection of group items that match the API request parameters. Optional: groupId."),
			mcplib.WithString("groupId", mcplib.Description("The `groupId` parameter specifies the unique ID of the group for which you want to retrieve group items.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v2/groupItems", false, []mcpParamBinding{{PublicName: "groupId", WireName: "groupId", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("groups_delete",
			mcplib.WithDescription("Deletes a group. Optional: id. Returns the EmptyResponse. Destructive."),
			mcplib.WithString("id", mcplib.Description("The `id` parameter specifies the YouTube group ID of the group that is being deleted.")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/v2/groups", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("groups_insert",
			mcplib.WithDescription("Creates a group. Optional: contentDetails, errors, etag (plus 3 more). Returns the new Group."),
			mcplib.WithString("contentDetails", mcplib.Description("A group's content details.")),
			mcplib.WithString("errors", mcplib.Description("Request Error information. The presence of an error field signals that the operation has failed.")),
			mcplib.WithString("etag", mcplib.Description("The Etag of this resource.")),
			mcplib.WithString("id", mcplib.Description("The ID that YouTube uses to uniquely identify the group.")),
			mcplib.WithString("kind", mcplib.Description("Identifies the API resource's type. The value will be `youtube#group`.")),
			mcplib.WithString("snippet", mcplib.Description("A group snippet.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/v2/groups", false, []mcpParamBinding{{PublicName: "contentDetails", WireName: "contentDetails", Location: "body"}, {PublicName: "errors", WireName: "errors", Location: "body"}, {PublicName: "etag", WireName: "etag", Location: "body"}, {PublicName: "id", WireName: "id", Location: "body"}, {PublicName: "kind", WireName: "kind", Location: "body"}, {PublicName: "snippet", WireName: "snippet", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("groups_list",
			mcplib.WithDescription("Returns a collection of groups that match the API request parameters. For example, you can retrieve all groups that the authenticated user owns, or you can retrieve one or more groups by their unique IDs. Optional: id, mine, pageToken."),
			mcplib.WithString("id", mcplib.Description("The `id` parameter specifies a comma-separated list of the YouTube group ID(s) for the resource(s) that are being...")),
			mcplib.WithBoolean("mine", mcplib.Description("This parameter can only be used in a properly authorized request. Set this parameter's value to true to retrieve all...")),
			mcplib.WithString("pageToken", mcplib.Description("The `pageToken` parameter identifies a specific page in the result set that should be returned. In an API response,...")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v2/groups", false, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}, {PublicName: "mine", WireName: "mine", Location: "query"}, {PublicName: "pageToken", WireName: "pageToken", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("groups_update",
			mcplib.WithDescription("Modifies a group. For example, you could change a group's title. Optional: contentDetails, errors, etag (plus 3 more). Returns the updated Group."),
			mcplib.WithString("contentDetails", mcplib.Description("A group's content details.")),
			mcplib.WithString("errors", mcplib.Description("Request Error information. The presence of an error field signals that the operation has failed.")),
			mcplib.WithString("etag", mcplib.Description("The Etag of this resource.")),
			mcplib.WithString("id", mcplib.Description("The ID that YouTube uses to uniquely identify the group.")),
			mcplib.WithString("kind", mcplib.Description("Identifies the API resource's type. The value will be `youtube#group`.")),
			mcplib.WithString("snippet", mcplib.Description("A group snippet.")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/v2/groups", false, []mcpParamBinding{{PublicName: "contentDetails", WireName: "contentDetails", Location: "body"}, {PublicName: "errors", WireName: "errors", Location: "body"}, {PublicName: "etag", WireName: "etag", Location: "body"}, {PublicName: "id", WireName: "id", Location: "body"}, {PublicName: "kind", WireName: "kind", Location: "body"}, {PublicName: "snippet", WireName: "snippet", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("reports_query",
			mcplib.WithDescription("Retrieve your YouTube Analytics reports. Optional: currency, dimensions, endDate (plus 8 more). Returns the QueryResponse."),
			mcplib.WithString("currency", mcplib.Description("The currency to which financial metrics should be converted. The default is US Dollar (USD). If the result contains...")),
			mcplib.WithString("dimensions", mcplib.Description("A comma-separated list of YouTube Analytics dimensions, such as `views` or `ageGroup,gender`. See the [Available...")),
			mcplib.WithString("endDate", mcplib.Description("The end date for fetching YouTube Analytics data. The value should be in `YYYY-MM-DD` format. required: true,...")),
			mcplib.WithString("filters", mcplib.Description("A list of filters that should be applied when retrieving YouTube Analytics data. The [Available...")),
			mcplib.WithString("ids", mcplib.Description("Identifies the YouTube channel or content owner for which you are retrieving YouTube Analytics data. - To request...")),
			mcplib.WithBoolean("includeHistoricalChannelData", mcplib.Description("If set to true historical data (i.e. channel data from before the linking of the channel to the content owner) will...")),
			mcplib.WithNumber("maxResults", mcplib.Description("The maximum number of rows to include in the response.', minValue: 1")),
			mcplib.WithString("metrics", mcplib.Description("A comma-separated list of YouTube Analytics metrics, such as `views` or `likes,dislikes`. See the [Available...")),
			mcplib.WithString("sort", mcplib.Description("A comma-separated list of dimensions or metrics that determine the sort order for YouTube Analytics data. By default...")),
			mcplib.WithString("startDate", mcplib.Description("The start date for fetching YouTube Analytics data. The value should be in `YYYY-MM-DD` format. required: true,...")),
			mcplib.WithNumber("startIndex", mcplib.Description("An index of the first entity to retrieve. Use this parameter as a pagination mechanism along with the max-results...")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v2/reports", false, []mcpParamBinding{{PublicName: "currency", WireName: "currency", Location: "query"}, {PublicName: "dimensions", WireName: "dimensions", Location: "query"}, {PublicName: "endDate", WireName: "endDate", Location: "query"}, {PublicName: "filters", WireName: "filters", Location: "query"}, {PublicName: "ids", WireName: "ids", Location: "query"}, {PublicName: "includeHistoricalChannelData", WireName: "includeHistoricalChannelData", Location: "query"}, {PublicName: "maxResults", WireName: "maxResults", Location: "query"}, {PublicName: "metrics", WireName: "metrics", Location: "query"}, {PublicName: "sort", WireName: "sort", Location: "query"}, {PublicName: "startDate", WireName: "startDate", Location: "query"}, {PublicName: "startIndex", WireName: "startIndex", Location: "query"}}, []string{}),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, binaryResponse bool, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if binaryResponse {
			headers = map[string]string{client.BinaryResponseHeader: "true"}
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if binaryResponse {
				data, err = c.GetWithHeaders(path, params, headers)
				break
			}
			data, err = c.Get(path, params)
		case "POST":
			if binaryResponse {
				data, _, err = c.PostWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PostWithParams(path, params, bodyArgs)
		case "PUT":
			if binaryResponse {
				data, _, err = c.PutWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(path, params, bodyArgs)
		case "PATCH":
			if binaryResponse {
				data, _, err = c.PatchWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(path, params, bodyArgs)
		case "DELETE":
			if binaryResponse {
				data, _, err = c.DeleteWithParamsAndHeaders(path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export YOUTUBE_ANALYTICS_OAUTH2C=<your-key>" +
					"\n      See API docs: https://google.com" +
					"\n      Run 'youtube-analytics-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Set it with: export YOUTUBE_ANALYTICS_OAUTH2C=<your-key>" +
					"\n      See API docs: https://google.com" +
					"\n      Run 'youtube-analytics-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export YOUTUBE_ANALYTICS_OAUTH2C=<your-key>" +
					"\n      See API docs: https://google.com" +
					"\n      Run 'youtube-analytics-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "youtube-analytics-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "youtube-analytics-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "youtube-analytics",
		"description": "The YouTube Analytics CLI with a local archive — period-over-period deltas, multi-channel rollups, and anomaly...",
		"archetype":   "generic",
		"tool_count":  8,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion youtube-analytics-pp-cli binary.",
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":        "YOUTUBE_ANALYTICS_OAUTH2C",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
			"docs_url": "https://google.com",
		},
		"resources": []map[string]any{
			{
				"name":        "group-items",
				"description": "Manage group items",
				"endpoints":   []string{"delete", "insert", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "groups",
				"description": "Manage groups",
				"endpoints":   []string{"delete", "insert", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "reports",
				"description": "Manage reports",
				"endpoints":   []string{"query"},
				"syncable":    true,
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass pageToken parameter for subsequent pages.",
			"Control page size with the maxResults parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Sync to local archive", "command": "sync", "description": "Pull daily YouTube Analytics rows into a local SQLite archive so trends, comparisons, and history work offline.", "rationale": "The API only returns the window a single call asks for and lags 2-3 days; a cursor-managed local archive with a...", "via": "mcp-command-mirror"},
			{"name": "Channel report card", "command": "report", "description": "Views, watch time, subscribers, and revenue for a period with the prior equal period and a delta beside each metric.", "rationale": "YouTube Analytics never returns period-over-period; the deltas are computed by joining current and prior rows in the...", "via": "mcp-command-mirror"},
			{"name": "Multi-channel rollup", "command": "rollup", "description": "Every registered channel side by side for one period, one row per channel, sorted by views or revenue.", "rationale": "No single YouTube Analytics call spans channels; this joins the channel registry against the archive.", "via": "mcp-command-mirror"},
			{"name": "What-changed digest", "command": "whatchanged", "description": "Diffs two periods across every synced dimension and ranks the biggest movers — traffic sources, videos, revenue.", "rationale": "A multi-dimension period diff that only exists once both periods are in the local archive.", "via": "mcp-command-mirror"},
			{"name": "Anomaly flag", "command": "anomaly", "description": "Flags metrics in the latest finalized period that fall outside the trailing mean and standard deviation.", "rationale": "Needs a statistical baseline; impossible from one API call, which has no history to compare against.", "via": "mcp-command-mirror"},
			{"name": "RPM tracker", "command": "rpm", "description": "Monthly RPM, CPM, and monetized playbacks as a stable series after trailing re-sync settles late revenue adjustments.", "rationale": "The live API revenue number keeps moving for weeks; the archive records what each month actually settled at.", "via": "mcp-command-mirror"},
			{"name": "Top-movers", "command": "movers", "description": "Ranks videos by week-over-week view delta, surfacing both risers and faders.", "rationale": "A video-versus-video, period-versus-period join no single API call returns.", "via": "mcp-command-mirror"},
			{"name": "SQL escape hatch", "command": "sql", "description": "Runs read-only SQL directly against the local analytics archive for any aggregation the presets do not cover.", "rationale": "Full query access to the SQLite archive — only possible because the data is stored locally.", "via": "mcp-command-mirror"},
			{"name": "Channel registry", "command": "channels", "description": "Maps friendly names like ScrollCore to channel IDs and credential sets so every command takes --channel by name.", "rationale": "A local name-to-ID mapping with no API call that makes natural-language, multi-channel addressing work.", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Sync to local archive", "insight": "The API only returns the window a single call asks for and lags 2-3 days; a cursor-managed local archive with a re-synced trailing window is the only way to hold real history."},
			{"topic": "Channel report card", "insight": "YouTube Analytics never returns period-over-period; the deltas are computed by joining current and prior rows in the local archive."},
			{"topic": "Multi-channel rollup", "insight": "No single YouTube Analytics call spans channels; this joins the channel registry against the archive."},
			{"topic": "What-changed digest", "insight": "A multi-dimension period diff that only exists once both periods are in the local archive."},
			{"topic": "Anomaly flag", "insight": "Needs a statistical baseline; impossible from one API call, which has no history to compare against."},
			{"topic": "RPM tracker", "insight": "The live API revenue number keeps moving for weeks; the archive records what each month actually settled at."},
			{"topic": "Top-movers", "insight": "A video-versus-video, period-versus-period join no single API call returns."},
			{"topic": "SQL escape hatch", "insight": "Full query access to the SQLite archive — only possible because the data is stored locally."},
			{"topic": "Channel registry", "insight": "A local name-to-ID mapping with no API call that makes natural-language, multi-channel addressing work."},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
