// Copyright 2026 Ryan Collins. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newGroupItemsInsertCmd(flags *rootFlags) *cobra.Command {
	var bodyErrorsCode string
	var bodyErrorsError string
	var bodyErrorsRequestId string
	var bodyEtag string
	var bodyGroupId string
	var bodyId string
	var bodyKind string
	var bodyResourceId string
	var bodyResourceKind string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "insert",
		Aliases:     []string{"create"},
		Short:       "Creates a group item.",
		Example:     "  youtube-analytics-pp-cli group-items insert",
		Annotations: map[string]string{"pp:endpoint": "group-items.insert", "pp:method": "POST", "pp:path": "/v2/groupItems"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v2/groupItems"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedErrors := map[string]any{}
					if bodyErrorsCode != "" {
						nestedErrors["code"] = bodyErrorsCode
					}
					if bodyErrorsError != "" {
						var parsedErrorsError any
						if err := json.Unmarshal([]byte(bodyErrorsError), &parsedErrorsError); err != nil {
							return fmt.Errorf("parsing --errors-error JSON: %w", err)
						}
						nestedErrors["error"] = parsedErrorsError
					}
					if bodyErrorsRequestId != "" {
						nestedErrors["requestId"] = bodyErrorsRequestId
					}
					if len(nestedErrors) > 0 {
						body["errors"] = nestedErrors
					}
				}
				if bodyEtag != "" {
					body["etag"] = bodyEtag
				}
				if bodyGroupId != "" {
					body["groupId"] = bodyGroupId
				}
				if bodyId != "" {
					body["id"] = bodyId
				}
				if bodyKind != "" {
					body["kind"] = bodyKind
				}
				{
					nestedResource := map[string]any{}
					if bodyResourceId != "" {
						nestedResource["id"] = bodyResourceId
					}
					if bodyResourceKind != "" {
						nestedResource["kind"] = bodyResourceKind
					}
					if len(nestedResource) > 0 {
						body["resource"] = nestedResource
					}
				}
			}
			data, statusCode, err := c.PostWithParams(path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "group-items", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "group-items", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "group-items", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "group-items", partialFailure.Message))
					}
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "group-items",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "group-items", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "group-items", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyErrorsCode, "errors-code", "", "Global error code. Deprecated and ignored. Set custom error codes in ErrorProto.domain and ErrorProto.code instead.")
	cmd.Flags().StringVar(&bodyErrorsError, "errors-error", "", "Specific error description and codes")
	cmd.Flags().StringVar(&bodyErrorsRequestId, "errors-request-id", "", "Request identifier generated by the service, which can be used to identify the error in the logs")
	cmd.Flags().StringVar(&bodyEtag, "etag", "", "The Etag of this resource.")
	cmd.Flags().StringVar(&bodyGroupId, "group-id", "", "The ID that YouTube uses to uniquely identify the group that contains the item.")
	cmd.Flags().StringVar(&bodyId, "id", "", "The ID that YouTube uses to uniquely identify the `channel`, `video`, `playlist`, or `asset` resource that is...")
	cmd.Flags().StringVar(&bodyKind, "kind", "", "Identifies the API resource's type. The value will be `youtube#groupItem`.")
	cmd.Flags().StringVar(&bodyResourceId, "resource-id", "", "The channel, video, playlist, or asset ID that YouTube uses to uniquely identify the item that is being added to the...")
	cmd.Flags().StringVar(&bodyResourceKind, "resource-kind", "", "Identifies the type of resource being added to the group. Valid values for this property are: * `youtube#channel` *...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
