// Copyright 2026 Ryan Collins. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/pelletier/go-toml/v2"
)

type Config struct {
	BaseURL       string            `toml:"base_url"`
	AuthHeaderVal string            `toml:"auth_header"`
	Headers       map[string]string `toml:"headers,omitempty"`
	AuthSource    string            `toml:"-"`
	AccessToken   string            `toml:"access_token"`
	RefreshToken  string            `toml:"refresh_token"`
	TokenExpiry   time.Time         `toml:"token_expiry"`
	ClientID      string            `toml:"client_id"`
	ClientSecret  string            `toml:"client_secret"`
	// AuthorizationURL overrides the spec-baked OAuth2 authorization endpoint.
	// Falls back to the generator default at the call site when empty so a
	// user pointing the CLI at a non-default deployment can override without
	// regenerating.
	AuthorizationURL string `toml:"authorization_url,omitempty"`
	// TokenURL overrides the spec-baked OAuth2 token endpoint. Same fallback
	// pattern as AuthorizationURL.
	TokenURL                string `toml:"token_url,omitempty"`
	Path                    string `toml:"-"`
	YoutubeAnalyticsOauth2c string `toml:"analytics_oauth2c"`
}

func Load(configPath string) (*Config, error) {
	cfg := &Config{
		BaseURL: "https://youtubeanalytics.googleapis.com",
	}

	// Resolve config path
	path := configPath
	if path == "" {
		path = os.Getenv("YOUTUBE_ANALYTICS_CONFIG")
	}
	if path == "" {
		home, _ := os.UserHomeDir()
		path = filepath.Join(home, ".config", "youtube-analytics-pp-cli", "config.toml")
	}
	cfg.Path = path

	// Try to load config file
	data, err := os.ReadFile(path)
	if err == nil {
		if err := toml.Unmarshal(data, cfg); err != nil {
			return nil, fmt.Errorf("parsing config %s: %w", path, err)
		}
	}

	// Env var overrides
	if v := os.Getenv("YOUTUBE_ANALYTICS_OAUTH2C"); v != "" {
		cfg.YoutubeAnalyticsOauth2c = v
		cfg.AuthSource = "env:YOUTUBE_ANALYTICS_OAUTH2C"
	}
	if v := os.Getenv("YOUTUBE_CLIENT_ID"); v != "" {
		cfg.ClientID = v
	}
	if v := os.Getenv("YOUTUBE_CLIENT_SECRET"); v != "" {
		cfg.ClientSecret = v
	}
	if v := os.Getenv("YOUTUBE_REFRESH_TOKEN"); v != "" {
		cfg.RefreshToken = v
		cfg.AuthSource = "env:YOUTUBE_REFRESH_TOKEN"
	}
	if v := os.Getenv("YOUTUBE_ACCESS_TOKEN"); v != "" {
		cfg.AccessToken = v
		cfg.AuthSource = "env:YOUTUBE_ACCESS_TOKEN"
	}

	// Label config-file-derived credentials so doctor can distinguish
	// "credentials persisted on disk" from "no credentials at all" — without
	// this, users who saved via set-token without an env var see a blank
	// auth_source and can't tell whether their config is being picked up.
	// The label is the literal "config" rather than "config:<path>"; the
	// config file path is exposed separately as report["config_path"], and
	// embedding it in auth_source leaks the user's home directory through
	// doctor's JSON envelope.
	if cfg.AuthSource == "" && (cfg.AuthHeaderVal != "" || cfg.AccessToken != "") {
		cfg.AuthSource = "config"
	}
	if cfg.AuthSource == "" && cfg.YoutubeAnalyticsOauth2c != "" {
		cfg.AuthSource = "config"
	}

	// Base URL override (used by printing-press verify to point at mock/test servers)
	if v := os.Getenv("YOUTUBE_ANALYTICS_BASE_URL"); v != "" {
		cfg.BaseURL = v
	}
	if v := os.Getenv("YOUTUBE_ANALYTICS_AUTHORIZATION_URL"); v != "" {
		cfg.AuthorizationURL = v
	}
	if v := os.Getenv("YOUTUBE_ANALYTICS_TOKEN_URL"); v != "" {
		cfg.TokenURL = v
	}
	if cfg.TokenURL == "" {
		cfg.TokenURL = "https://oauth2.googleapis.com/token"
	}
	return cfg, nil
}

func (c *Config) AuthHeader() string {
	if c.AuthHeaderVal != "" {
		return c.AuthHeaderVal
	}
	// Env-var token wins over file-stored AccessToken (env > config convention).
	if c.YoutubeAnalyticsOauth2c != "" {
		c.AuthSource = "env:YOUTUBE_ANALYTICS_OAUTH2C"
		return "Bearer " + c.YoutubeAnalyticsOauth2c
	}
	if c.AccessToken != "" {
		c.AuthSource = "oauth2"
		return "Bearer " + c.AccessToken
	}
	return ""
}

func applyAuthFormat(format string, replacements map[string]string) string {
	if format == "" {
		return ""
	}
	for key, value := range replacements {
		format = strings.ReplaceAll(format, "{"+key+"}", value)
	}
	if strings.Contains(format, "{") {
		return ""
	}
	return format
}

func (c *Config) SaveTokens(clientID, clientSecret, accessToken, refreshToken string, expiry time.Time) error {
	c.ClientID = clientID
	c.ClientSecret = clientSecret
	c.AccessToken = accessToken
	c.RefreshToken = refreshToken
	c.TokenExpiry = expiry
	return c.save()
}

func (c *Config) ClearTokens() error {
	// AuthHeader() falls back to the env-var-derived fields when AuthHeaderVal
	// and AccessToken are empty, so dropping the working credential requires
	// zeroing every emitted credential field, not just the OAuth trio.
	// ClientID/ClientSecret persist to disk via SaveTokens for the oauth2
	// and oauth2-cc flows, so logout must wipe them too; otherwise
	// `auth login` can re-mint a new access token unattended.
	c.AuthHeaderVal = ""
	c.AccessToken = ""
	c.RefreshToken = ""
	c.TokenExpiry = time.Time{}
	c.ClientID = ""
	c.ClientSecret = ""
	c.YoutubeAnalyticsOauth2c = ""
	return c.save()
}

func (c *Config) save() error {
	dir := filepath.Dir(c.Path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}
	data, err := toml.Marshal(c)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}
	return os.WriteFile(c.Path, data, 0o600)
}

// Ensure strings import is used
var _ = strings.ReplaceAll
